import { useEffect, useRef, useState } from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import { api } from "../../api/client";
import ErrorAlert from "../ui/ErrorAlert";
import { useLocale } from "../../context/LocaleContext";

const field="w-full rounded-xl border border-[var(--brand-border)] bg-[var(--brand-surface)] px-3 py-2";
function RouteMap({route,onPick}){
 const ref=useRef(null), mapRef=useRef(null),layerRef=useRef(null),pickRef=useRef(onPick);pickRef.current=onPick;
 useEffect(()=>{if(mapRef.current)return;const map=L.map(ref.current).setView([41.0,69.0],6);L.tileLayer(import.meta.env.VITE_MAP_TILE_URL||"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);map.on("click",e=>pickRef.current?.(e.latlng));mapRef.current=map;return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;if(layerRef.current)layerRef.current.remove();const group=L.layerGroup().addTo(map);layerRef.current=group;const pts=route?.geometry||[];if(pts.length){L.polyline(pts,{color:"#2563eb",weight:5}).addTo(group);pts.forEach((p,i)=>L.circleMarker(p,{radius:9,color:i===0?"#16a34a":i===pts.length-1?"#dc2626":"#2563eb",fillOpacity:1}).bindTooltip(String(i===0?"A":i===pts.length-1?"B":i),{permanent:true,direction:"center"}).addTo(group));map.fitBounds(L.latLngBounds(pts).pad(.15));}},[route]);
 return <div ref={ref} className="h-[420px] min-w-0 rounded-xl border"/>;
}
export default function TripRoutePlanner({tripId}){
 const {t,locale}=useLocale();const [route,setRoute]=useState(null),[error,setError]=useState(""),[pick,setPick]=useState("origin"),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({origin_name:"",origin_lat:"",origin_lon:"",destination_name:"",destination_lat:"",destination_lon:""});
 const [stop,setStop]=useState({name:"",address:"",latitude:"",longitude:"",notes:""});
 const [editingStopId,setEditingStopId]=useState(null);
 const load=async()=>{try{const r=await api.finishedTripRoute(tripId);setRoute(r.route);if(r.route)setForm({origin_name:r.route.origin.name,origin_lat:r.route.origin.latitude,origin_lon:r.route.origin.longitude,destination_name:r.route.destination.name,destination_lat:r.route.destination.latitude,destination_lon:r.route.destination.longitude});setError("")}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[tripId]);
 const picked=({lat,lng})=>{if(pick==="stop")setStop(x=>({...x,latitude:lat.toFixed(6),longitude:lng.toFixed(6)}));else setForm(x=>({...x,[`${pick}_lat`]:lat.toFixed(6),[`${pick}_lon`]:lng.toFixed(6)}))};
 const save=async()=>{setBusy(true);try{const body={...form,origin_lat:Number(form.origin_lat),origin_lon:Number(form.origin_lon),destination_lat:Number(form.destination_lat),destination_lon:Number(form.destination_lon)};setRoute(route?await api.finishedTripRouteUpdate(tripId,{...body,expected_version:route.version}):await api.finishedTripRouteCreate(tripId,body));setError("")}catch(e){setError(e.message)}finally{setBusy(false)}};
 const clearStop=()=>{setEditingStopId(null);setStop({name:"",address:"",latitude:"",longitude:"",notes:""})};
 const saveStop=async()=>{try{const body={...stop,expected_version:route.version,sequence:editingStopId?undefined:route.stops.length+1,stop_type:"waypoint",latitude:Number(stop.latitude),longitude:Number(stop.longitude),planned_arrival_at:null};setRoute(editingStopId?await api.finishedTripRouteStopUpdate(tripId,editingStopId,body):await api.finishedTripRouteStopCreate(tripId,body));clearStop();setError("")}catch(e){setError(e.message)}};
 const editStop=s=>{setEditingStopId(s.id);setStop({name:s.name,address:s.address||"",latitude:String(s.latitude),longitude:String(s.longitude),notes:s.notes||""})};
 const removeStop=async id=>{try{setRoute(await api.finishedTripRouteStopDelete(tripId,id,route.version));if(editingStopId===id)clearStop();setError("")}catch(e){setError(e.message)}};
 const moveStop=async(index,delta)=>{const next=index+delta;if(next<0||next>=route.stops.length)return;const ids=route.stops.map(s=>s.id);[ids[index],ids[next]]=[ids[next],ids[index]];try{setRoute(await api.finishedTripRouteStopsReorder(tripId,{expected_version:route.version,stop_ids:ids}));setError("")}catch(e){setError(e.message)}};
 const status=async(value)=>{try{setRoute(await api.finishedTripRouteStatus(tripId,{expected_version:route.version,status:value}))}catch(e){setError(e.message)}};
 const km=route?.planned_distance_m!=null?(route.planned_distance_m/1000).toLocaleString(locale==="ru"?"ru-RU":"uz-UZ",{maximumFractionDigits:1}):"—";
 return <div className="grid min-w-0 gap-4 xl:grid-cols-[340px_minmax(0,1fr)_280px]">
  <section className="space-y-3 rounded-2xl border bg-[var(--brand-surface)] p-4"><h2 className="font-black">{t("tripRoute.form")}</h2>{error&&<ErrorAlert message={error}/>} {["origin","destination"].map(k=><div key={k} className="space-y-2"><label className="font-bold">{t(`tripRoute.${k}`)}</label><input className={field} placeholder={t("tripRoute.name")} value={form[`${k}_name`]} onChange={e=>setForm({...form,[`${k}_name`]:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className={field} inputMode="decimal" value={form[`${k}_lat`]} onChange={e=>setForm({...form,[`${k}_lat`]:e.target.value})}/><input className={field} inputMode="decimal" value={form[`${k}_lon`]} onChange={e=>setForm({...form,[`${k}_lon`]:e.target.value})}/></div><button className="rounded-xl border px-3 py-2" onClick={()=>setPick(k)}>{t("tripRoute.pickMap")}</button></div>)}<button disabled={busy} className="brand-btn w-full rounded-xl px-3 py-2 text-white" onClick={save}>{t("tripRoute.save")}</button>
  {route&&<div className="space-y-2 border-t pt-3"><h3 className="font-bold">{t(editingStopId?"tripRoute.editStop":"tripRoute.addStop")}</h3><input className={field} placeholder={t("tripRoute.name")} value={stop.name} onChange={e=>setStop({...stop,name:e.target.value})}/><input className={field} placeholder={t("tripRoute.address")} value={stop.address} onChange={e=>setStop({...stop,address:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className={field} value={stop.latitude} onChange={e=>setStop({...stop,latitude:e.target.value})}/><input className={field} value={stop.longitude} onChange={e=>setStop({...stop,longitude:e.target.value})}/></div><button className="rounded-xl border px-3 py-2" onClick={()=>setPick("stop")}>{t("tripRoute.pickMap")}</button><div className="flex flex-wrap gap-2"><button className="rounded-xl border px-3 py-2" onClick={saveStop}>{t(editingStopId?"tripRoute.updateStop":"tripRoute.addStop")}</button>{editingStopId&&<button className="rounded-xl border px-3 py-2" onClick={clearStop}>{t("tripRoute.cancel")}</button>}</div></div>}</section>
  <RouteMap route={route} onPick={picked}/>
  <aside className="space-y-3 rounded-2xl border bg-[var(--brand-surface)] p-4"><h2 className="font-black">{t("tripRoute.summary")}</h2><p>{t("tripRoute.status")}: <strong>{route?t(`tripRoute.statuses.${route.status}`):"—"}</strong></p><p>{t("tripRoute.distance")}: <strong>{km} km</strong></p><p>{t("tripRoute.duration")}: <strong>{route?Math.round(route.planned_duration_s/60):"—"} {t("tripRoute.minutes")}</strong></p><p className="text-xs text-amber-700">{t("tripRoute.manualNotice")}</p><ol className="space-y-2">{route?.stops.map((s,i)=><li key={s.id} className="rounded-xl border p-2"><strong>{s.sequence}. {s.name}</strong><small className="block">{s.address||"—"}</small><div className="mt-2 flex flex-wrap gap-1"><button aria-label={`${t("tripRoute.moveUp")} ${s.name}`} disabled={i===0} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-40" onClick={()=>moveStop(i,-1)}>↑ {t("tripRoute.moveUp")}</button><button aria-label={`${t("tripRoute.moveDown")} ${s.name}`} disabled={i===route.stops.length-1} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-40" onClick={()=>moveStop(i,1)}>↓ {t("tripRoute.moveDown")}</button><button className="rounded-lg border px-2 py-1 text-xs" onClick={()=>editStop(s)}>{t("tripRoute.editStop")}</button><button className="rounded-lg border px-2 py-1 text-xs text-red-700" onClick={()=>removeStop(s.id)}>{t("tripRoute.removeStop")}</button></div></li>)}</ol>{route?.status==="draft"&&<button className="brand-btn w-full rounded-xl px-3 py-2 text-white" onClick={()=>status("active")}>{t("tripRoute.activate")}</button>}{route&&!['cancelled','completed'].includes(route.status)&&<button className="w-full rounded-xl border px-3 py-2" onClick={()=>status("cancelled")}>{t("tripRoute.cancel")}</button>}</aside>
 </div>;
}
