name: velcore_driver
description: Velcore ERP — haydovchi GPS ilovasi (Android)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  background_locator_2: ^2.0.6
  workmanager: ^0.5.2
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  battery_plus: ^6.2.1
  connectivity_plus: ^6.1.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
