import { useEffect, useState } from "react";
import { api } from "../../api/client";
import { useLocale } from "../../context/LocaleContext";

const reasons=["incorrect_completion","quality_issue","repaint","reweld","incorrect_quantity","operator_error","other"];
const key=(prefix)=>`${prefix}-${Date.now()}-${crypto.randomUUID()}`;

export default function StageCorrectionPanel({job,onChanged,canManage}){
  const {t}=useLocale(); const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [history,setHistory]=useState([]),[form,setForm]=useState({job_line_id:"",quantity:"",reason_code:"repaint",comment:""});
  const diagnostic=(job?.qc_parts||[]).some(x=>x.qc_diagnostic_code==="QC-RECONCILE-PAINT-ACCEPTANCE");
  const load=async()=>{if(!job?.project_id)return;try{const r=await api.productionJobCorrectionHistory(job.id);setHistory(r.events||[])}catch{/* main job remains authoritative */}};
  useEffect(()=>{load()},[job?.id]);
  const run=async(fn)=>{setBusy(true);setMessage("");try{await fn();await onChanged();await load();setMessage(t("stageCorrection.saved"));setOpen(false)}catch(e){setMessage(t(`stageCorrection.errors.${e.code||"generic"}`))}finally{setBusy(false)}};
  if(!job?.project_id||!canManage)return null;
  return <section className="mt-4 rounded-2xl border bg-[var(--brand-card)] p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-bold">{t("stageCorrection.title")}</h3><div className="flex flex-wrap gap-2"><button disabled={busy} className="min-h-11 rounded-xl border px-4 font-bold disabled:opacity-50" onClick={()=>run(()=>api.productionJobStageReopen(job.id,{stage:"kraska",reason_code:"incorrect_completion",comment:t("stageCorrection.saved"),operation_key:key("stage-reopen")}))}>{t("stageCorrection.types.stage_reopened")} · {t("stageCorrection.paintStage")}</button><button className="min-h-11 rounded-xl border px-4 font-bold" onClick={()=>setOpen(v=>!v)}>{t("stageCorrection.returnAction")}</button></div></div>
    {diagnostic?<div className="mt-3 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><p>{t("stageCorrection.paintReconcileHint")}</p><button disabled={busy} className="mt-2 min-h-11 rounded-xl bg-amber-700 px-4 font-bold text-white" onClick={()=>run(()=>api.productionJobPaintReconcile(job.id,{reason:t("stageCorrection.paintReconcileReason")}))}>{t("stageCorrection.reconcilePaint")}</button></div>:null}
    {open?<div role="dialog" aria-label={t("stageCorrection.returnAction")} className="mt-4 grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><label>{t("stageCorrection.currentStage")}<input disabled value={t("stageCorrection.qcStage")} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label>{t("stageCorrection.targetStage")}<input disabled value={t("stageCorrection.paintStage")} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label>{t("stageCorrection.availableQty")}<select className="mt-1 min-h-11 w-full rounded-xl border px-3" value={form.job_line_id} onChange={e=>{const row=(job.qc_parts||[]).find(x=>String(x.id)===e.target.value);setForm(f=>({...f,job_line_id:e.target.value,quantity:String((Number(row?.accepted_quantity)||0)+(Number(row?.rework_quantity)||0))}))}}><option value="">—</option>{(job.qc_parts||[]).map(x=><option value={x.id} key={x.id}>{x.part_number} · {Number(x.accepted_quantity||0)+Number(x.rework_quantity||0)}</option>)}</select></label><label>{t("stageCorrection.returnQty")}<input type="number" min="0" step="any" className="mt-1 min-h-11 w-full rounded-xl border px-3" value={form.quantity} onChange={e=>setForm(f=>({...f,quantity:e.target.value}))}/></label><label>{t("stageCorrection.reason")}<select className="mt-1 min-h-11 w-full rounded-xl border px-3" value={form.reason_code} onChange={e=>setForm(f=>({...f,reason_code:e.target.value}))}>{reasons.map(x=><option key={x} value={x}>{t(`stageCorrection.reasons.${x}`)}</option>)}</select></label><label>{t("stageCorrection.comment")}<textarea className="mt-1 w-full rounded-xl border px-3 py-2" value={form.comment} onChange={e=>setForm(f=>({...f,comment:e.target.value}))}/></label><button disabled={busy||!form.job_line_id||!Number(form.quantity)} className="min-h-11 rounded-xl bg-[var(--brand-button)] font-bold text-white disabled:opacity-50 sm:col-span-2" onClick={()=>run(()=>api.productionJobStageReturn(job.id,{...form,job_line_id:Number(form.job_line_id),quantity:Number(form.quantity),source_stage:"qc",destination_stage:"painting",operation_key:key("stage-return")}))}>{t("stageCorrection.confirmReturn")}</button></div>:null}
    {message?<p className="mt-3 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>:null}{history.length?<div className="mt-4 space-y-2"><h4 className="font-bold">{t("stageCorrection.history")}</h4>{history.map(x=><div className="rounded-xl border p-3 text-sm" key={x.id}><b>{t(`stageCorrection.types.${x.type}`)}</b><span className="ml-2">{x.quantity} {t("stageCorrection.units")}</span><p>{t(`stageCorrection.reasons.${x.reason_code}`)} · {x.actor} · {x.occurred_at}</p>{x.comment?<p>{x.comment}</p>:null}</div>)}</div>:null}
  </section>;
}
