param(
    [Parameter(Mandatory = $true)]
    [string]$ApiUrl
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppRoot = Resolve-Path (Join-Path $ScriptDir "..\..\..")
if (Test-Path "D:\AzmusERP\Application\frontend\package.json") {
    $AppRoot = "D:\AzmusERP\Application"
}

$FrontendDir = Join-Path $AppRoot "frontend"
if (!(Test-Path (Join-Path $FrontendDir "package.json"))) {
    throw "frontend\package.json not found under $AppRoot"
}

if ($ApiUrl.EndsWith("/")) {
    $ApiUrl = $ApiUrl.TrimEnd("/")
}

$envFile = Join-Path $FrontendDir ".env.production.local"
@"
# Generated by build_remote_frontend.ps1.
# The ERP database remains local at D:\AzmusERP\Data\database\azmus.db.
VITE_API_URL=$ApiUrl
VITE_TRACEABILITY_ENABLED=false
VITE_PRINT_AGENT_ENABLED=false
"@ | Set-Content -Encoding UTF8 $envFile

Write-Host "Building frontend with VITE_API_URL=$ApiUrl"
Push-Location $FrontendDir
try {
    npm run build
}
finally {
    Pop-Location
}

Write-Host "Frontend build complete: $FrontendDir\dist"

