# Quick remote access: local DB + public HTTPS via trycloudflare.com (no account).
# Database stays at D:\AzmusERP\Data\database\azmus.db — never Render/cloud DB.
param(
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppRoot = Resolve-Path (Join-Path $ScriptDir "..\..\..")
if (Test-Path "D:\AzmusERP\Application\backend\main.py") {
    $AppRoot = "D:\AzmusERP\Application"
}

$DbPath = "D:\AzmusERP\Data\database\azmus.db"
$LogPath = "D:\AzmusERP\Data\logs"
$UrlFile = Join-Path $LogPath "remote_access_urls.txt"

if (!(Test-Path $DbPath)) {
    throw "Production database not found: $DbPath"
}
New-Item -ItemType Directory -Force -Path $LogPath | Out-Null

$Cloudflared = & (Join-Path $ScriptDir "ensure_cloudflared.ps1")

function Test-PortListening([int]$Port) {
    return [bool](Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue)
}

function Wait-TunnelUrl([string[]]$LogFiles, [int]$TimeoutSec = 90) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        foreach ($LogFile in $LogFiles) {
            if (!(Test-Path $LogFile)) { continue }
            $text = Get-Content $LogFile -Raw -ErrorAction SilentlyContinue
            if (-not $text) { continue }
            foreach ($m in [regex]::Matches($text, 'https://[a-z0-9-]+\.trycloudflare\.com')) {
                $url = $m.Value
                # Ignore Cloudflare API hostnames that appear in error messages
                if ($url -match 'https://api\.trycloudflare\.com$') { continue }
                return $url
            }
        }
        Start-Sleep -Seconds 2
    }
    throw "Timed out waiting for tunnel URL in $($LogFiles -join ', ')"
}

function Test-TunnelHealth([string]$PublicUrl, [switch]$HtmlOk) {
    for ($i = 0; $i -lt 8; $i++) {
        try {
            if ($HtmlOk) {
                $r = Invoke-WebRequest -Uri $PublicUrl -UseBasicParsing -TimeoutSec 25
                if ($r.StatusCode -ge 200 -and $r.StatusCode -lt 400) { return $true }
            } else {
                $r = Invoke-RestMethod -Uri "$PublicUrl/" -TimeoutSec 25
                if ($r.status -eq 'ok') { return $true }
            }
        } catch {
            # trycloudflare URLs can take ~10s to become reachable
        }
        Start-Sleep -Seconds 3
    }
    return $false
}

function Start-BackendIfNeeded {
    if (Test-PortListening 8000) {
        Write-Host "Backend already on port 8000"
        return
    }
    Write-Host "Starting backend (D:\AzmusERP\Data\database\azmus.db) ..."
    $backendDir = Join-Path $AppRoot "backend"
    $cmd = @"
cd /d "$backendDir"
set DATA_ROOT=D:\AzmusERP\Data
set DB_PATH=D:\AzmusERP\Data\database\azmus.db
set UPLOAD_PATH=D:\AzmusERP\Data\uploads
set DATABASE_GUARD=true
set SKIP_DEMO_SEED=true
python -m uvicorn main:app --host 127.0.0.1 --port 8000 >> "$LogPath\uvicorn.out.log" 2>&1
"@
    Start-Process cmd.exe -ArgumentList "/c", $cmd -WindowStyle Minimized
    $deadline = (Get-Date).AddSeconds(30)
    while ((Get-Date) -lt $deadline) {
        if (Test-PortListening 8000) { return }
        Start-Sleep -Seconds 1
    }
    throw "Backend failed to start on port 8000"
}

function Stop-PortProcess([int]$Port) {
    Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
        ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue }
}

function Start-FrontendIfNeeded([string]$ApiUrl) {
    $frontendDir = Join-Path $AppRoot "frontend"
    $envLocal = Join-Path $frontendDir ".env.production.local"
    $remoteApiJson = Join-Path $frontendDir "public\remote-api.json"
    @"
# Auto-generated by start_quick_tunnel.ps1 — API tunnel URL
VITE_API_URL=$ApiUrl
VITE_TRACEABILITY_ENABLED=false
VITE_PRINT_AGENT_ENABLED=false
"@ | Set-Content -Encoding UTF8 $envLocal

    $remoteJsonContent = @"
{
  "apiUrl": "$ApiUrl",
  "updatedAt": "$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss')"
}
"@
    Write-Utf8NoBom $remoteApiJson $remoteJsonContent
    Copy-Item $remoteApiJson (Join-Path $LogPath "remote-api.json") -Force

    if (!$SkipBuild -or !(Test-Path (Join-Path $frontendDir "dist\index.html"))) {
        Write-Host "Building frontend with VITE_API_URL=$ApiUrl ..."
        Push-Location $frontendDir
        try {
            $env:VITE_API_URL = $ApiUrl
            $buildLog = Join-Path $LogPath "vite-build.log"
            $build = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "npm run build > `"$buildLog`" 2>&1" -WorkingDirectory $frontendDir -Wait -PassThru -NoNewWindow
            if ($build.ExitCode -ne 0) {
                throw "npm run build failed (exit $($build.ExitCode)). See $buildLog"
            }
        }
        finally {
            Pop-Location
        }
    }

    if (Test-PortListening 5173) {
        Write-Host "Restarting frontend preview (new API URL baked in) ..."
        Stop-PortProcess 5173
        Start-Sleep -Seconds 2
    }
    Write-Host "Starting frontend preview on 0.0.0.0:5173 ..."
    Start-Process cmd.exe -ArgumentList "/c", "cd /d `"$frontendDir`" && npm run preview:prod >> `"$LogPath\vite-preview.out.log`" 2>&1" -WindowStyle Minimized
    $deadline = (Get-Date).AddSeconds(45)
    while ((Get-Date) -lt $deadline) {
        if (Test-PortListening 5173) { return }
        Start-Sleep -Seconds 1
    }
    throw "Frontend failed to start on port 5173"
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Start-Tunnel([string]$Name, [string]$TargetUrl) {
    $outLog = Join-Path $LogPath "cloudflared-$Name.out.log"
    $errLog = Join-Path $LogPath "cloudflared-$Name.err.log"
    foreach ($f in @($outLog, $errLog)) {
        if (Test-Path $f) { Remove-Item $f -Force }
    }
    $proc = Start-Process -FilePath $Cloudflared -ArgumentList @(
        "tunnel", "--url", $TargetUrl, "--no-autoupdate"
    ) -RedirectStandardOutput $outLog -RedirectStandardError $errLog -WindowStyle Hidden -PassThru
    $url = Wait-TunnelUrl @($errLog, $outLog) -TimeoutSec 120
    return @{ Url = $url; ProcessId = $proc.Id; Name = $Name }
}

# --- Main ---
Get-Process cloudflared -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Seconds 1

Start-BackendIfNeeded

$health = Invoke-RestMethod -Uri "http://127.0.0.1:8000/" -TimeoutSec 15
if ($health.database -notlike "*AzmusERP*") {
    Write-Warning "Unexpected database path: $($health.database)"
}

Write-Host "Starting API tunnel (port 8000) ..."
$apiPublic = $null
for ($attempt = 1; $attempt -le 3; $attempt++) {
    if ($attempt -gt 1) {
        Write-Host "Retrying API tunnel (attempt $attempt) ..."
        Get-Process cloudflared -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
    }
    $apiPublic = Start-Tunnel "api" "http://127.0.0.1:8000"
    $apiPublic = $apiPublic.Url
    Write-Host "  candidate: $apiPublic"
    if (Test-TunnelHealth $apiPublic) { break }
    Write-Warning "API tunnel not reachable yet: $apiPublic"
    $apiPublic = $null
}
if (-not $apiPublic) {
    throw "API tunnel failed after 3 attempts. Check D:\AzmusERP\Data\logs\cloudflared-api.err.log"
}
Write-Host "API public URL: $apiPublic"

Start-FrontendIfNeeded -ApiUrl $apiPublic

Write-Host "Starting UI tunnel (port 5173) ..."
$uiPublic = $null
for ($attempt = 1; $attempt -le 3; $attempt++) {
    if ($attempt -gt 1) {
        Write-Host "Retrying UI tunnel (attempt $attempt) ..."
        Start-Sleep -Seconds 5
    }
    try {
        $uiResult = Start-Tunnel "ui" "http://127.0.0.1:5173"
        $uiPublic = $uiResult.Url
        Write-Host "  candidate: $uiPublic"
        if (Test-TunnelHealth $uiPublic -HtmlOk) { break }
    } catch {
        Write-Warning $_.Exception.Message
        $uiPublic = $null
    }
}
if (-not $uiPublic -or -not (Test-TunnelHealth $uiPublic -HtmlOk)) {
    throw "UI tunnel failed after 3 attempts. Check D:\AzmusERP\Data\logs\cloudflared-ui.err.log"
}
Write-Host "UI public URL: $uiPublic"

$lanIp = & (Join-Path $ScriptDir "get_lan_ip.ps1")

$summary = @"
Azmus ERP Quick Tunnel — $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Database: D:\AzmusERP\Data\database\azmus.db (orders=$($health.orders_count))

PUBLIC (phone / internet):
  UI:  $uiPublic
  API: $apiPublic

LOCAL PC:
  UI:  http://127.0.0.1:5173
  API: http://127.0.0.1:8000

OFFICE LAN:
  UI:  http://${lanIp}:5173
  API: http://${lanIp}:8000

GPS pages (public):
  $uiPublic/driver-tracking
  $uiPublic/transport/live-map

NOTE: trycloudflare URLs change every restart. Re-run this script after reboot.
"@

$summary | Tee-Object -FilePath $UrlFile
Write-Host $summary
