"""Make brigades independent from terminals and add flexible terminal assignments."""

from sqlalchemy import inspect, text


TABLE = "mes_terminal_brigade_assignments"


def upgrade_brigade_terminal_assignments(engine):
    if engine.dialect.name != "postgresql":
        print(
            f"BRIGADE TERMINAL ASSIGNMENTS MIGRATION SKIPPED: "
            f"{engine.dialect.name}"
        )
        return

    inspector = inspect(engine)
    existing = set(inspector.get_table_names())

    required_tables = {
        "mes_terminal_brigades",
        "mes_production_stages",
    }
    if not required_tables.issubset(existing):
        print(
            "BRIGADE TERMINAL ASSIGNMENTS MIGRATION SKIPPED: "
            "required tables missing"
        )
        return

    with engine.begin() as conn:
        conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {TABLE} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                brigade_id INTEGER NOT NULL
                    REFERENCES mes_terminal_brigades(id) ON DELETE CASCADE,
                stage_id INTEGER NOT NULL
                    REFERENCES mes_production_stages(id) ON DELETE CASCADE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_by VARCHAR(100) NOT NULL DEFAULT '',
                updated_by VARCHAR(100) NOT NULL DEFAULT '',
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
        """))

        conn.execute(text(f"""
            CREATE UNIQUE INDEX IF NOT EXISTS
                uq_mes_terminal_brigade_assignment
            ON {TABLE}(brigade_id, stage_id)
        """))

        conn.execute(text(f"""
            CREATE INDEX IF NOT EXISTS
                ix_mes_terminal_brigade_assignments_brigade_id
            ON {TABLE}(brigade_id)
        """))

        conn.execute(text(f"""
            CREATE INDEX IF NOT EXISTS
                ix_mes_terminal_brigade_assignments_stage_id
            ON {TABLE}(stage_id)
        """))

        # Old stage/name constraint makes a brigade permanently stage-oriented.
        # Remove it; terminal membership is now controlled by the assignment table.
        conn.execute(text("""
            ALTER TABLE mes_terminal_brigades
            DROP CONSTRAINT IF EXISTS uq_mes_terminal_brigade_stage_name
        """))

        # stage_id remains temporarily for backward compatibility with old rows.
        # It is no longer the source of truth for terminal assignment.
        conn.execute(text("""
            ALTER TABLE mes_terminal_brigades
            ALTER COLUMN stage_id DROP NOT NULL
        """))

    print("BRIGADE TERMINAL ASSIGNMENTS MIGRATION COMPLETED")
