"""Professional finance module migration.

Additive only:
- keeps legacy incomes/expenses untouched
- supports PostgreSQL and SQLite
- creates finance master data and transaction tables
"""

from sqlalchemy import inspect, text


MIGRATION_NAME = "2026_09_14_finance_professional"


def _dt_type(dialect_name: str) -> str:
    return "TIMESTAMP WITHOUT TIME ZONE" if dialect_name == "postgresql" else "DATETIME"


def upgrade(engine) -> None:
    inspector = inspect(engine)
    existing_tables = set(inspector.get_table_names())
    dt = _dt_type(engine.dialect.name)

    statements = [
        f"""
        CREATE TABLE IF NOT EXISTS finance_accounts (
            id INTEGER PRIMARY KEY {'GENERATED BY DEFAULT AS IDENTITY' if engine.dialect.name == 'postgresql' else 'AUTOINCREMENT'},
            code VARCHAR(40) NOT NULL UNIQUE,
            name_uz VARCHAR(160) NOT NULL,
            name_ru VARCHAR(160) NOT NULL,
            account_type VARCHAR(24) NOT NULL,
            currency_code VARCHAR(8) NOT NULL DEFAULT 'UZS',
            opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
            current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at {dt},
            updated_at {dt}
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS finance_categories (
            id INTEGER PRIMARY KEY {'GENERATED BY DEFAULT AS IDENTITY' if engine.dialect.name == 'postgresql' else 'AUTOINCREMENT'},
            code VARCHAR(64) NOT NULL UNIQUE,
            name_uz VARCHAR(160) NOT NULL,
            name_ru VARCHAR(160) NOT NULL,
            category_type VARCHAR(24) NOT NULL,
            parent_id INTEGER,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at {dt},
            updated_at {dt},
            FOREIGN KEY (parent_id) REFERENCES finance_categories(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS finance_counterparties (
            id INTEGER PRIMARY KEY {'GENERATED BY DEFAULT AS IDENTITY' if engine.dialect.name == 'postgresql' else 'AUTOINCREMENT'},
            name VARCHAR(255) NOT NULL,
            counterparty_type VARCHAR(24) NOT NULL DEFAULT 'other',
            tax_id VARCHAR(64) DEFAULT '',
            phone VARCHAR(64) DEFAULT '',
            email VARCHAR(160) DEFAULT '',
            address TEXT DEFAULT '',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at {dt},
            updated_at {dt}
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS finance_transactions (
            id INTEGER PRIMARY KEY {'GENERATED BY DEFAULT AS IDENTITY' if engine.dialect.name == 'postgresql' else 'AUTOINCREMENT'},
            document_no VARCHAR(64) NOT NULL UNIQUE,
            transaction_type VARCHAR(24) NOT NULL,
            account_id INTEGER NOT NULL,
            category_id INTEGER,
            counterparty_id INTEGER,
            amount NUMERIC(18,2) NOT NULL,
            currency_code VARCHAR(8) NOT NULL DEFAULT 'UZS',
            exchange_rate NUMERIC(18,6) NOT NULL DEFAULT 1,
            amount_uzs NUMERIC(18,2) NOT NULL DEFAULT 0,
            description TEXT DEFAULT '',
            project_id INTEGER,
            status VARCHAR(24) NOT NULL DEFAULT 'posted',
            transaction_date {dt} NOT NULL,
            created_by VARCHAR(100) DEFAULT '',
            created_at {dt},
            updated_at {dt},
            FOREIGN KEY (account_id) REFERENCES finance_accounts(id),
            FOREIGN KEY (category_id) REFERENCES finance_categories(id),
            FOREIGN KEY (counterparty_id) REFERENCES finance_counterparties(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS finance_transfers (
            id INTEGER PRIMARY KEY {'GENERATED BY DEFAULT AS IDENTITY' if engine.dialect.name == 'postgresql' else 'AUTOINCREMENT'},
            document_no VARCHAR(64) NOT NULL UNIQUE,
            from_account_id INTEGER NOT NULL,
            to_account_id INTEGER NOT NULL,
            amount NUMERIC(18,2) NOT NULL,
            commission_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
            description TEXT DEFAULT '',
            transfer_date {dt} NOT NULL,
            created_by VARCHAR(100) DEFAULT '',
            created_at {dt},
            FOREIGN KEY (from_account_id) REFERENCES finance_accounts(id),
            FOREIGN KEY (to_account_id) REFERENCES finance_accounts(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS finance_obligations (
            id INTEGER PRIMARY KEY {'GENERATED BY DEFAULT AS IDENTITY' if engine.dialect.name == 'postgresql' else 'AUTOINCREMENT'},
            obligation_type VARCHAR(16) NOT NULL,
            counterparty_id INTEGER NOT NULL,
            project_id INTEGER,
            document_no VARCHAR(64) DEFAULT '',
            original_amount NUMERIC(18,2) NOT NULL,
            paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
            currency_code VARCHAR(8) NOT NULL DEFAULT 'UZS',
            due_date {dt},
            status VARCHAR(24) NOT NULL DEFAULT 'open',
            description TEXT DEFAULT '',
            created_at {dt},
            updated_at {dt},
            FOREIGN KEY (counterparty_id) REFERENCES finance_counterparties(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS finance_obligation_payments (
            id INTEGER PRIMARY KEY {'GENERATED BY DEFAULT AS IDENTITY' if engine.dialect.name == 'postgresql' else 'AUTOINCREMENT'},
            obligation_id INTEGER NOT NULL,
            account_id INTEGER,
            transaction_id INTEGER,
            amount NUMERIC(18,2) NOT NULL,
            currency_code VARCHAR(8) NOT NULL DEFAULT 'UZS',
            payment_date {dt} NOT NULL,
            payment_method VARCHAR(32) DEFAULT '',
            document_no VARCHAR(64) DEFAULT '',
            description TEXT DEFAULT '',
            created_by VARCHAR(100) DEFAULT '',
            created_at {dt},
            FOREIGN KEY (obligation_id) REFERENCES finance_obligations(id),
            FOREIGN KEY (account_id) REFERENCES finance_accounts(id),
            FOREIGN KEY (transaction_id) REFERENCES finance_transactions(id)
        )
        """,
    ]

    with engine.begin() as connection:
        for sql in statements:
            connection.execute(text(sql))

        indexes = [
            ("ix_finance_accounts_type", "finance_accounts", "account_type"),
            ("ix_finance_categories_type", "finance_categories", "category_type"),
            ("ix_finance_transactions_date", "finance_transactions", "transaction_date"),
            ("ix_finance_transactions_account", "finance_transactions", "account_id"),
            ("ix_finance_transactions_project", "finance_transactions", "project_id"),
            ("ix_finance_obligations_type", "finance_obligations", "obligation_type"),
            ("ix_finance_obligations_counterparty", "finance_obligations", "counterparty_id"),
            ("ix_finance_obligation_payments_obligation", "finance_obligation_payments", "obligation_id"),
            ("ix_finance_obligation_payments_date", "finance_obligation_payments", "payment_date"),
        ]

        tables = set(inspect(connection).get_table_names())
        for index_name, table_name, column_name in indexes:
            if table_name not in tables:
                continue
            existing = {i["name"] for i in inspect(connection).get_indexes(table_name)}
            if index_name not in existing:
                connection.execute(
                    text(f"CREATE INDEX {index_name} ON {table_name} ({column_name})")
                )


def downgrade(engine) -> None:
    raise RuntimeError(
        "Destructive finance downgrade requires an explicitly reviewed migration"
    )
