"""Add MES terminal brigades and production-operation participants."""

from sqlalchemy import inspect, text


def _has_column(inspector, table_name, column_name):
    return any(c["name"] == column_name for c in inspector.get_columns(table_name))


def _has_table(inspector, table_name):
    return table_name in set(inspector.get_table_names())


def _has_constraint(inspector, table_name, name):
    return any(
        c.get("name") == name
        for c in inspector.get_unique_constraints(table_name)
    )


def upgrade_production_brigades(engine):
    if engine.dialect.name != "postgresql":
        print(f"PRODUCTION BRIGADES MIGRATION SKIPPED: {engine.dialect.name}")
        return

    inspector = inspect(engine)

    required_tables = {
        "users",
        "mes_production_stages",
        "project_production_operations",
    }
    existing = set(inspector.get_table_names())
    if not required_tables.issubset(existing):
        print("PRODUCTION BRIGADES MIGRATION SKIPPED: required tables missing")
        return

    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS mes_terminal_brigades (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stage_id INTEGER NOT NULL
                    REFERENCES mes_production_stages(id),
                name VARCHAR(120) NOT NULL,
                brigadier_user_id INTEGER NOT NULL
                    REFERENCES users(id),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_by VARCHAR(100) NOT NULL DEFAULT '',
                updated_by VARCHAR(100) NOT NULL DEFAULT '',
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
        """))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS mes_terminal_brigade_members (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                brigade_id INTEGER NOT NULL
                    REFERENCES mes_terminal_brigades(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL
                    REFERENCES users(id),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
        """))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS project_production_operation_participants (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                operation_id INTEGER NOT NULL
                    REFERENCES project_production_operations(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL
                    REFERENCES users(id),
                participation_role VARCHAR(20) NOT NULL,
                full_name_snapshot VARCHAR(160) NOT NULL DEFAULT '',
                employee_id_snapshot VARCHAR(80) NOT NULL DEFAULT '',
                position_snapshot VARCHAR(120) NOT NULL DEFAULT '',
                started_at TIMESTAMP NULL,
                completed_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                CONSTRAINT ck_operation_participant_role
                    CHECK (participation_role IN ('brigadier', 'worker'))
            )
        """))

        inspector = inspect(engine)

        if not _has_column(
            inspector,
            "project_production_operations",
            "brigade_id",
        ):
            conn.execute(text("""
                ALTER TABLE project_production_operations
                ADD COLUMN brigade_id INTEGER NULL
                REFERENCES mes_terminal_brigades(id)
            """))

        inspector = inspect(engine)

        conn.execute(text("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'uq_mes_terminal_brigade_stage_name'
                ) THEN
                    ALTER TABLE mes_terminal_brigades
                    ADD CONSTRAINT uq_mes_terminal_brigade_stage_name
                    UNIQUE (stage_id, name);
                END IF;
            END
            $$;
        """))

        conn.execute(text("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'uq_mes_terminal_brigade_member'
                ) THEN
                    ALTER TABLE mes_terminal_brigade_members
                    ADD CONSTRAINT uq_mes_terminal_brigade_member
                    UNIQUE (brigade_id, user_id);
                END IF;
            END
            $$;
        """))

        conn.execute(text("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'uq_operation_participant_user_role'
                ) THEN
                    ALTER TABLE project_production_operation_participants
                    ADD CONSTRAINT uq_operation_participant_user_role
                    UNIQUE (operation_id, user_id, participation_role);
                END IF;
            END
            $$;
        """))

        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_mes_terminal_brigades_stage_id
            ON mes_terminal_brigades(stage_id)
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_mes_terminal_brigades_brigadier_user_id
            ON mes_terminal_brigades(brigadier_user_id)
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_mes_terminal_brigade_members_brigade_id
            ON mes_terminal_brigade_members(brigade_id)
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_mes_terminal_brigade_members_user_id
            ON mes_terminal_brigade_members(user_id)
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_project_operation_participants_operation_id
            ON project_production_operation_participants(operation_id)
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_project_operation_participants_user_id
            ON project_production_operation_participants(user_id)
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_project_production_operations_brigade_id
            ON project_production_operations(brigade_id)
        """))

    print("PRODUCTION BRIGADES MIGRATION COMPLETED")
