import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Card from "../../components/ui/Card";
import ErrorAlert from "../../components/ui/ErrorAlert";
import LoadingSpinner from "../../components/ui/LoadingSpinner";
import PageHeader from "../../components/ui/PageHeader";
import { api, authenticatedFetch } from "../../api/client";
import { useLocale } from "../../context/LocaleContext";

const STATUS_KEYS={created:"statusCreated",packed:"statusPacked",received:"statusReceived",in_warehouse:"statusWarehouse",placed:"statusPlaced",loaded:"statusLoaded",shipped:"statusShipped",dispatched:"statusShipped",in_transit:"statusTransit",arrived:"statusArrived",delivered:"statusDelivered",accepted:"statusAccepted",finished:"statusFinished",completed:"statusFinished"};
const RESULT_KEYS={qc_pass:"qcPass",qc_fail:"qcFail",rework_completed:"reworkCompleted",pending:"issuePending",completed:"issueCompleted",created:"resultCreated",released:"resultReleased",loaded:"resultLoaded",dispatched:"resultDispatched",in_transit:"resultTransit",arrived:"resultArrived",delivered:"resultDelivered",accepted:"resultAccepted"};
const statusLabel=(t,value)=>value?t(`traceability.${STATUS_KEYS[String(value).toLowerCase()]||"statusUnknown"}`):"—";
const statusTone=(value)=>({delivered:"green",accepted:"green",arrived:"blue",shipped:"blue",in_transit:"blue",loaded:"blue",packed:"amber"}[String(value||"").toLowerCase()]||"slate");
const stageLabel=(t,row)=>{const key=String(row?.stage_key||row?.stage_name||"").toLowerCase().replace(/[^a-z0-9]+/g,"_");const known={project:"stageProject",mes_release:"stageRelease",lazer:"stageLazer",laser:"stageLazer",svarka:"stageSvarka",svarshik:"stageSvarka",kraska:"stageKraska",painting:"stageKraska",qc:"stageQc",inspection:"stageQc",packaging:"stagePackaging",upakovka:"stagePackaging",warehouse:"stageWarehouse",sklad:"stageWarehouse",loading:"stageLoading",yuklash:"stageLoading",dispatch:"stageDispatch",gps_in_transit:"stageGps",arrival:"stageArrival",delivery:"stageDelivery",acceptance:"stageAcceptance"}[key]||(key.startsWith("rework_")?"rework":null);return known?t(`traceability.${known}`):(row?.stage_name||"—");};
const resultLabel=(t,value)=>RESULT_KEYS[value]?t(`traceability.${RESULT_KEYS[value]}`):t("traceability.resultUnknown");
const localError=(t,error)=>{const key={passport_generation_not_ready:"errorNotReady",traceability_view_required:"errorViewRequired",traceability_generate_required:"errorGenerateRequired",traceability_print_required:"errorPrintRequired",passport_not_found:"notFound",network_error:"errorNetwork",traceability_batch_invalid:"errorBatch"}[error?.code];return key?t(`traceability.${key}`):(error?.message||t("traceability.error"));};
const showDate=(formatDateTime,value)=>{try{return value?formatDateTime(value):"—";}catch{return "—";}};

function Badge({children,tone="slate"}){const cls={green:"bg-emerald-50 text-emerald-700 ring-emerald-200",amber:"bg-amber-50 text-amber-700 ring-amber-200",red:"bg-red-50 text-red-700 ring-red-200",blue:"bg-blue-50 text-blue-700 ring-blue-200",slate:"bg-slate-50 text-slate-700 ring-slate-200"}[tone];return <span className={`inline-flex whitespace-nowrap rounded-full px-2 py-1 text-xs font-semibold ring-1 ring-inset ${cls}`}>{children}</span>;}
function QrPreview({serial,title}){const [src,setSrc]=useState("");useEffect(()=>{let alive=true,url="";(async()=>{try{const response=await authenticatedFetch(api.productPassportLabelUrl(serial,"60x60"));if(response.ok){url=URL.createObjectURL(await response.blob());if(alive)setSrc(url);}}catch{/* preview is non-blocking */}})();return()=>{alive=false;if(url)URL.revokeObjectURL(url);};},[serial]);return src?<img src={src} alt={title} className="h-11 w-11 rounded-lg border border-slate-200 bg-white object-cover"/>:<div aria-label={title} className="h-11 w-11 animate-pulse rounded-lg bg-slate-100"/>;}
async function download(url,filename,options){const response=await authenticatedFetch(url,options);if(!response.ok)throw new Error(`HTTP ${response.status}`);const objectUrl=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=objectUrl;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);}
function Section({title,children}){return <Card className="overflow-hidden !p-0"><div className="border-b border-slate-200 bg-slate-900 px-4 py-3 text-sm font-bold text-white">{title}</div><div className="p-4">{children}</div></Card>;}
function DataTable({headers,children}){return <div className="max-w-full overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr>{headers.map((x,i)=><th key={`${x}-${i}`} className="whitespace-nowrap px-3 py-2.5 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{children}</tbody></table></div>;}

function Detail({data,t,language,formatDateTime}){
  const [busy,setBusy]=useState("");const [error,setError]=useState("");const quality=data.quality?.issues||[];const shipment=data.shipment||{};const pkg=data.package||{};
  const exportFile=async(format)=>{setBusy(format);setError("");try{const ext=format==="label"?"png":format;const url=format==="label"?api.productPassportLabelUrl(data.serial_number):api.productPassportDocumentUrl(data.serial_number,format,language);await download(url,`${data.serial_number}-${format==="label"?"label":"passport"}.${ext}`);}catch(e){setError(localError(t,e));}finally{setBusy("");}};
  return <div className="space-y-4"><PageHeader title={`${t("traceability.passportTitle")} · ${data.serial_number}`} subtitle={t("traceability.passportSubtitle")}/>
    <div className="flex flex-wrap gap-2">{[["pdf","PDF"],["docx",t("traceability.word")],["xlsx",t("traceability.excel")],["label",t("traceability.printLabel")]].map(([key,label])=><button key={key} type="button" disabled={!!busy} onClick={()=>exportFile(key)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-800 shadow-sm hover:border-blue-400 hover:text-blue-700 disabled:opacity-50">{busy===key?t("common.loading"):label}</button>)}</div>{error?<ErrorAlert message={error}/>:null}
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 space-y-4">
      <Section title={t("traceability.productInformation")}><DataTable headers={[t("traceability.serial"),t("traceability.productCode"),t("traceability.productName"),t("traceability.project"),t("traceability.currentStatus"),t("traceability.producedAt")]}><tr>{[data.serial_number,data.product_code,data.product_name,[data.project?.code,data.project?.name].filter(Boolean).join(" — "),<Badge key="status" tone="blue">{statusLabel(t,data.status)}</Badge>,showDate(formatDateTime,data.created_at)].map((v,i)=><td key={i} className="whitespace-nowrap px-3 py-3 font-medium">{v||"—"}</td>)}</tr></DataTable></Section>
      <Section title={t("traceability.productionHistory")}><DataTable headers={[t("traceability.stage"),t("traceability.operator"),t("traceability.startedAt"),t("traceability.completedAt"),t("traceability.duration"),t("traceability.result")]}>{(data.timeline||[]).map(row=><tr key={row.stage_key}><td className="px-3 py-3 font-semibold">{stageLabel(t,row)}</td><td className="px-3 py-3">{row.operator||t("traceability.actorUnavailable")}</td><td className="whitespace-nowrap px-3 py-3">{showDate(formatDateTime,row.started_at)}</td><td className="whitespace-nowrap px-3 py-3">{showDate(formatDateTime,row.completed_at)}</td><td className="px-3 py-3">{row.duration_seconds==null?"—":`${Math.round(row.duration_seconds/60)} ${t("traceability.minutes")}`}</td><td className="px-3 py-3"><Badge tone={String(row.result).includes("fail")?"red":String(row.result).includes("pass")||String(row.result).includes("completed")?"green":"blue"}>{resultLabel(t,row.result)}</Badge></td></tr>)}</DataTable></Section>
      <Section title={t("traceability.qcRework")}><DataTable headers={[t("traceability.issue"),t("traceability.status"),t("traceability.detectedBy"),t("traceability.detectedAt"),t("traceability.reworkActor"),t("traceability.reworkCompletedAt")]}>{quality.length?quality.map(issue=><tr key={issue.id}><td className="px-3 py-3">{issue.notes||t("traceability.rework")}</td><td className="px-3 py-3"><Badge tone={issue.status==="completed"?"green":"amber"}>{resultLabel(t,issue.status)}</Badge></td><td className="px-3 py-3">{issue.detected_by||t("traceability.actorUnavailable")}</td><td className="px-3 py-3">{showDate(formatDateTime,issue.detected_at)}</td><td className="px-3 py-3">{issue.resolved_by||t("traceability.actorUnavailable")}</td><td className="px-3 py-3">{showDate(formatDateTime,issue.resolved_at)}</td></tr>):<tr><td colSpan="6" className="px-3 py-6 text-center text-slate-500">{t("traceability.noIssues")}</td></tr>}</DataTable></Section>
      <Section title={t("traceability.packagingInformation")}><DataTable headers={[t("traceability.package"),t("traceability.status"),t("traceability.createdAt"),t("traceability.netWeight"),t("traceability.grossWeight")]}><tr>{[pkg.number,statusLabel(t,pkg.status),showDate(formatDateTime,pkg.created_at),`${pkg.net_weight_kg||0} kg`,`${pkg.gross_weight_kg||0} kg`].map((v,i)=><td key={i} className="px-3 py-3">{v||"—"}</td>)}</tr></DataTable></Section>
      <Section title={t("traceability.logisticsInformation")}><DataTable headers={[t("traceability.shipment"),t("traceability.status"),t("traceability.destination"),t("traceability.vehicle"),t("traceability.driver"),t("traceability.deliveredAt")]}><tr>{[shipment.trip_number||shipment.dispatch_number,statusLabel(t,shipment.status),shipment.destination,shipment.vehicle,shipment.driver,showDate(formatDateTime,shipment.delivered_at)].map((v,i)=><td key={i} className="px-3 py-3">{v||"—"}</td>)}</tr></DataTable></Section>
    </div><Section title={t("traceability.qrPanel")}><div className="flex flex-col items-center text-center"><QrPreview serial={data.serial_number} title={t("traceability.qrPreview")}/><p className="mt-3 font-mono text-sm font-bold text-slate-900">{data.serial_number}</p><p className="mt-2 text-xs leading-5 text-slate-500">{t("traceability.qrHelp")}</p><button type="button" onClick={()=>exportFile("label")} className="mt-4 w-full rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">{t("traceability.printLabel")}</button></div></Section></div>
  </div>;
}

export default function ProductTraceabilityPage(){
  const {serial}=useParams();const {t,language,formatDateTime}=useLocale();const [items,setItems]=useState([]);const [dashboard,setDashboard]=useState(null);const [detail,setDetail]=useState(null);const [selected,setSelected]=useState([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [filters,setFilters]=useState({serial:"",product:"",project:"",package:"",trip:"",date_from:"",date_to:"",with_issues:false});const seq=useRef(0);
  const load=async()=>{const id=++seq.current;setLoading(true);setError("");try{if(serial){const result=await api.traceabilityProduct(serial);if(id===seq.current)setDetail(result);}else{const [list,stats]=await Promise.all([api.traceabilityProducts(filters),api.traceabilityDashboard()]);if(id===seq.current){setItems(list.items||[]);setDashboard(stats);setSelected([]);}}}catch(e){if(id===seq.current)setError(localError(t,e));}finally{if(id===seq.current)setLoading(false);}};
  useEffect(()=>{setDetail(null);load();},[serial]);
  if(loading)return <div className="flex min-h-[35vh] items-center justify-center"><LoadingSpinner label={t("traceability.loading")}/></div>;
  if(serial)return error?<ErrorAlert message={error}/>:detail?<Detail data={detail} t={t} language={language} formatDateTime={formatDateTime}/>:<ErrorAlert message={t("traceability.notFound")}/>;
  const chosen=selected.length?selected:items.map(x=>x.serial_number);const batch=async(kind)=>{if(!chosen.length)return;setBusy(kind);setError("");try{const excel=kind==="excel";await download(excel?api.traceabilityBatchExcelUrl():api.traceabilityBatchLabelPdfUrl(),excel?"product-passports.xlsx":"product-passports-60x60.pdf",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(excel?{serial_numbers:chosen,language}:{serial_numbers:chosen,size:"60x60"})});}catch(e){setError(localError(t,e));}finally{setBusy("");}};
  const kpis=[["total",dashboard?.passport_total??items.length,"blue"],["producedToday",dashboard?.passport_produced_today??0,"blue"],["warehouse",dashboard?.passport_packed??0,"amber"],["shipped",dashboard?.passport_shipped??0,"blue"],["delivered",dashboard?.passport_delivered??0,"green"],["issues",dashboard?.passport_issues??0,"red"]];
  return <div className="space-y-4"><PageHeader title={t("traceability.dashboardTitle")} subtitle={t("traceability.dashboardSubtitle")}/>{error?<ErrorAlert message={error}/>:null}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{kpis.map(([key,value,tone])=><Card key={key} className={`border-l-4 !p-4 ${tone==="green"?"border-l-emerald-600":tone==="amber"?"border-l-amber-600":tone==="red"?"border-l-red-600":"border-l-blue-600"}`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t(`traceability.${key}`)}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></Card>)}</div>
    <Card><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" onSubmit={e=>{e.preventDefault();load();}}>{[["serial","text"],["product","text"],["project","text"],["package","text"],["shipment","text"],["dateFrom","date"],["dateTo","date"]].map(([key,type])=>{const field={shipment:"trip",dateFrom:"date_from",dateTo:"date_to"}[key]||key;return <label key={key} className="text-sm font-semibold text-slate-700">{t(`traceability.${key}`)}<input type={type} value={filters[field]} onChange={e=>setFilters({...filters,[field]:e.target.value})} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2"/></label>;})}<label className="flex items-center gap-2 self-end pb-2 text-sm font-semibold"><input type="checkbox" checked={filters.with_issues} onChange={e=>setFilters({...filters,with_issues:e.target.checked})}/>{t("traceability.withIssues")}</label><button type="submit" className="self-end rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{t("traceability.applyFilters")}</button></form></Card>
    <Card className="!p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><div><h2 className="font-bold text-slate-950">{t("traceability.products")}</h2><p className="text-xs text-slate-500">{t("traceability.selectedCount",{count:selected.length})}</p></div><div className="flex flex-wrap gap-2"><button disabled={!chosen.length||!!busy} onClick={()=>batch("excel")} className="rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-50">{busy==="excel"?t("common.loading"):t("traceability.exportSelectedExcel")}</button><button disabled={!chosen.length||!!busy} onClick={()=>batch("labels")} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy==="labels"?t("common.loading"):t("traceability.batchPrintLabels")}</button></div></div>
      {items.length?<DataTable headers={["",t("traceability.qrPreview"),t("traceability.serial"),t("traceability.productCode"),t("traceability.productName"),t("traceability.project"),t("traceability.package"),t("traceability.currentStatus"),t("traceability.qcStatus"),t("traceability.producedAt"),t("traceability.shipment"),t("traceability.actions")]}>{items.map(row=>{const checked=selected.includes(row.serial_number);const issues=row.quality?.issue_count||0;return <tr key={row.serial_number} className="hover:bg-slate-50"><td className="px-3 py-3"><input aria-label={t("traceability.selectPassport")} type="checkbox" checked={checked} onChange={()=>setSelected(checked?selected.filter(x=>x!==row.serial_number):[...selected,row.serial_number])}/></td><td className="px-3 py-3"><QrPreview serial={row.serial_number} title={t("traceability.qrPreview")}/></td><td className="whitespace-nowrap px-3 py-3 font-mono text-xs font-bold">{row.serial_number}</td><td className="whitespace-nowrap px-3 py-3">{row.product_code||"—"}</td><td className="min-w-48 px-3 py-3 font-semibold">{row.product_name||"—"}</td><td className="whitespace-nowrap px-3 py-3">{row.project?.code||"—"}</td><td className="whitespace-nowrap px-3 py-3">{row.package?.number||"—"}</td><td className="px-3 py-3"><Badge tone={statusTone(row.status)}>{statusLabel(t,row.status)}</Badge></td><td className="px-3 py-3"><Badge tone={issues?"red":"green"}>{issues?t("traceability.qcIssue"):t("traceability.qcPass")}</Badge></td><td className="whitespace-nowrap px-3 py-3">{showDate(formatDateTime,row.created_at)}</td><td className="whitespace-nowrap px-3 py-3">{row.shipment?.trip_number||row.shipment?.dispatch_number||"—"}</td><td className="px-3 py-3"><div className="flex min-w-max gap-2"><Link className="font-semibold text-blue-700 hover:underline" to={`/traceability/products/${encodeURIComponent(row.serial_number)}`}>{t("traceability.openPassport")}</Link><button onClick={()=>download(api.productPassportLabelUrl(row.serial_number),`${row.serial_number}.png`)} className="text-slate-600 hover:text-blue-700">QR</button><button onClick={()=>download(api.productPassportDocumentUrl(row.serial_number,"pdf",language),`${row.serial_number}.pdf`)} className="text-slate-600 hover:text-blue-700">PDF</button><button onClick={()=>download(api.productPassportDocumentUrl(row.serial_number,"docx",language),`${row.serial_number}.docx`)} className="text-slate-600 hover:text-blue-700">{t("traceability.word")}</button><button onClick={()=>download(api.productPassportDocumentUrl(row.serial_number,"xlsx",language),`${row.serial_number}.xlsx`)} className="text-slate-600 hover:text-blue-700">{t("traceability.excel")}</button></div></td></tr>;})}</DataTable>:<p className="p-8 text-center text-sm text-slate-500">{t("traceability.noPassports")}</p>}</Card>
  </div>;
}
