import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../../api/client";
import { useAuth } from "../../context/AuthContext";
import { useLocale } from "../../context/LocaleContext";
import ErrorAlert from "../../components/ui/ErrorAlert";
import { Skeleton } from "../../components/ui/Skeleton";
import { apiMessage, date, field, number, panel, projectStatuses } from "./projectUi";

export default function ProductionProjectsPage() {
  const { t, locale } = useLocale(); const { hasPermission } = useAuth(); const navigate = useNavigate();
  const [filters, setFilters] = useState({ q: "", status: "", priority: "", destination: "", page: 1, page_size: 20 });
  const [state, setState] = useState({ loading: true, error: "", data: { items: [], total: 0 } });
  const load = useCallback(async () => { setState(s => ({ ...s, loading: true, error: "" })); try { const data = await api.productionProjects(filters); setState({ loading: false, error: "", data }); } catch (e) { setState(s => ({ ...s, loading: false, error: apiMessage(e, t) })); } }, [filters, t]);
  useEffect(() => { const timer = setTimeout(load, 200); return () => clearTimeout(timer); }, [load]);
  const pages = Math.max(1, Math.ceil(state.data.total / filters.page_size));
  const rows = useMemo(() => state.data.items.map(p => ({ ...p, total: Number(p.total_ordered_quantity || 0), count: Number(p.line_count || 0) })), [state.data.items]);
  return <section className="min-w-0 space-y-4">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black">{t("checkpointD.projects.title")}</h1><p className="text-sm text-[var(--brand-muted)]">{t("checkpointD.projects.subtitle")}</p></div>{hasPermission("production_projects_edit") && <Link to="/production-projects/new" className="brand-btn rounded-xl px-4 py-2 font-bold text-white">{t("checkpointD.actions.create")}</Link>}</header>
    <div className={`${panel} grid gap-3 md:grid-cols-4`} role="search"><input className={field} aria-label={t("checkpointD.actions.search")} placeholder={t("checkpointD.projects.search")} value={filters.q} onChange={e => setFilters({ ...filters, q: e.target.value, page: 1 })}/><select className={field} aria-label={t("checkpointD.fields.status")} value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value, page: 1 })}><option value="">{t("checkpointD.filters.allStatuses")}</option>{projectStatuses.map(x => <option key={x} value={x}>{t(`checkpointD.status.${x}`)}</option>)}</select><input className={field} aria-label={t("checkpointD.fields.destination")} placeholder={t("checkpointD.fields.destination")} value={filters.destination} onChange={e => setFilters({ ...filters, destination: e.target.value, page: 1 })}/><select className={field} aria-label={t("checkpointD.fields.priority")} value={filters.priority} onChange={e => setFilters({ ...filters, priority: e.target.value, page: 1 })}><option value="">{t("checkpointD.filters.allPriorities")}</option>{["low","normal","high","urgent"].map(x => <option key={x} value={x}>{t(`checkpointD.priority.${x}`)}</option>)}</select></div>
    {state.error && <ErrorAlert message={state.error} onRetry={load}/>} {state.loading ? <div className="space-y-3"><Skeleton className="h-20"/><Skeleton className="h-20"/></div> : rows.length === 0 ? <div className={`${panel} text-center text-[var(--brand-muted)]`}>{t("checkpointD.projects.empty")}</div> : <><div className="hidden overflow-x-auto rounded-2xl border md:block"><table className="w-full min-w-[960px] text-sm"><thead><tr className="bg-[var(--brand-background)] text-left">{["project","customer","destination","deadline","priority","quantity","production","logistics","updated"].map(k => <th key={k} className="p-3">{t(`checkpointD.fields.${k}`)}</th>)}</tr></thead><tbody>{rows.map(p => <tr key={p.id} className="border-t hover:bg-black/5" onDoubleClick={() => navigate(`/production-projects/${p.id}`)}><td className="p-3"><Link className="font-bold text-[var(--brand-primary)]" to={`/production-projects/${p.id}`}>{p.project_code}</Link><div>{p.project_name}</div></td><td className="p-3">{p.customer_name_snapshot}</td><td className="p-3">{p.destination_city || "—"}<div className="text-xs text-[var(--brand-muted)]">{p.site_name}</div></td><td className="p-3">{date(p.required_delivery_date, locale)}</td><td className="p-3">{t(`checkpointD.priority.${p.priority}`)}</td><td className="p-3">{number(p.total, locale)} · {p.count}</td><td className="p-3">{t(`checkpointD.status.${p.status}`)}</td><td className="p-3">{p.status === "completed" ? t("checkpointD.status.accepted") : p.status === "shipped" ? t("checkpointD.status.dispatched") : "—"}</td><td className="p-3">{date(p.updated_at, locale)}</td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{rows.map(p => <Link to={`/production-projects/${p.id}`} key={p.id} className={panel}><div className="flex justify-between gap-2"><strong>{p.project_code} · {p.project_name}</strong><span>{t(`checkpointD.priority.${p.priority}`)}</span></div><p>{p.customer_name_snapshot} · {p.destination_city || "—"}</p><p className="text-sm text-[var(--brand-muted)]">{number(p.total, locale)} · {t(`checkpointD.status.${p.status}`)}</p></Link>)}</div></>}
    <nav className="flex items-center justify-center gap-3" aria-label={t("checkpointD.pagination.label")}><button className="rounded-lg border px-3 py-2" disabled={filters.page <= 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>{t("checkpointD.pagination.previous")}</button><span>{filters.page} / {pages}</span><button className="rounded-lg border px-3 py-2" disabled={filters.page >= pages} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>{t("checkpointD.pagination.next")}</button></nav>
  </section>;
}
