import { useBranding } from "../../context/BrandingContext";
import { useLocale } from "../../context/LocaleContext";

export default function AppearanceTab() {
  const { branding } = useBranding();
  const { language, theme, clockFormat, setLanguage, setTheme, useOrganizationTheme, setClockFormat, t } = useLocale();
  const field = "w-full rounded-xl border border-[var(--brand-input-border)] bg-[var(--brand-input-background)] px-4 py-3 text-[var(--brand-input-text)]";
  return <div className="space-y-6">
    <header><h2 className="text-xl font-black">{t("settingsAppearance.title")}</h2><p className="text-sm text-[var(--brand-muted)]">{t("settingsAppearance.description")}</p></header>
    <section className="brand-card rounded-2xl border p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><h3 className="font-bold">{t("settingsAppearance.personalOverrides")}</h3><p className="text-sm text-[var(--brand-muted)]">{t("settingsAppearance.organizationValue", { value: t(`appearance.theme${branding.theme_mode === "dark" ? "Dark" : branding.theme_mode === "light" ? "Light" : "Auto"}`) })}</p></div><button type="button" className="brand-btn brand-btn-secondary px-4 py-2 text-sm font-bold" onClick={useOrganizationTheme}>{t("settingsAppearance.useOrganization")}</button></div>
      <div className="grid gap-4 sm:grid-cols-3"><label><span className="mb-1 block text-sm font-bold">{t("appearance.theme")}</span><select className={field} value={theme} onChange={(e)=>setTheme(e.target.value)}><option value="light">{t("appearance.themeLight")}</option><option value="dark">{t("appearance.themeDark")}</option><option value="auto">{t("appearance.themeAuto")}</option></select></label><label><span className="mb-1 block text-sm font-bold">{t("appearance.language")}</span><select className={field} value={language} onChange={(e)=>setLanguage(e.target.value)}><option value="uz">{t("organization.uzbekLatin")}</option><option value="ru">{t("organization.russian")}</option></select></label><label><span className="mb-1 block text-sm font-bold">{t("appearance.clockFormat")}</span><select className={field} value={clockFormat} onChange={(e)=>setClockFormat(e.target.value)}><option value="24h">{t("settingsAppearance.clock24")}</option><option value="12h">{t("settingsAppearance.clock12")}</option></select></label></div>
    </section>
    <section className="brand-card rounded-2xl border p-6"><h3 className="font-bold">{t("settingsAppearance.organizationManaged")}</h3><p className="mt-2 text-sm text-[var(--brand-muted)]">{t("settingsAppearance.organizationManagedDescription")}</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-lg border border-[var(--brand-border)] px-3 py-2">{t("appearance.colors.color_button")}</span><span className="rounded-lg border border-[var(--brand-border)] px-3 py-2">{t("appearance.colors.color_sidebar")}</span><span className="rounded-lg border border-[var(--brand-border)] px-3 py-2">{t("appearance.colors.color_background")}</span></div></section>
  </div>;
}
