import { useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { api, getApiBase } from "../api/client";

const styleFor = (s = {}) => ({ position: "absolute", left: `${s.x ?? 0}%`, top: `${s.y ?? 0}%`, width: `${s.width ?? 100}%`, height: `${s.height ?? 100}%`, zIndex: s.z_index ?? 1, background: s.background || "transparent", borderRadius: s.border_radius ?? 0, opacity: s.opacity ?? 1, transform: `rotate(${s.rotation ?? 0}deg)`, color: s.color || "inherit", fontFamily: s.font || "inherit", padding: s.padding ?? 0, margin: s.margin ?? 0 });
function ClockWidget({ settings }) { const [now, setNow] = useState(new Date()); useEffect(() => { const id = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(id); }, []); return <div style={styleFor(settings)} className="grid place-items-center text-[clamp(3rem,10vw,12rem)] font-black">{now.toLocaleTimeString()}</div>; }
function DateWidget({ settings }) { return <div style={styleFor(settings)} className="grid place-items-center text-[clamp(2rem,5vw,6rem)]">{new Date().toLocaleDateString(undefined, { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</div>; }
function TextWidget({ settings, title }) { return <div style={styleFor(settings)} className="grid place-items-center text-center text-[clamp(1.5rem,5vw,6rem)] font-bold">{settings.text || title}</div>; }
function MediaWidget({ media, settings, type }) { const src = media?.path?.startsWith("http") ? media.path : `${getApiBase()}${media?.path || settings.url || ""}`; if (type === "video") return <video style={styleFor(settings)} className="object-cover" src={src} autoPlay muted loop playsInline />; if (type === "pdf") return <iframe style={styleFor(settings)} title="PDF" src={src} />; return <img style={styleFor(settings)} className="object-contain" src={src} alt="Display media" />; }
function RenderWidget({ item }) { const settings = { ...(item.widget?.settings_json || {}), ...(item.settings_json || {}) }; const type = item.widget?.widget_type || item.item_type; if (type === "clock") return <ClockWidget settings={settings} />; if (type === "date") return <DateWidget settings={settings} />; if (["image", "video", "pdf"].includes(type) || item.media) return <MediaWidget media={item.media} settings={settings} type={type === "document" ? "pdf" : type} />; return <TextWidget settings={settings} title={type.replaceAll("_", " ")} />; }
const cacheRuntime = async (code, payload) => { localStorage.setItem(`display-runtime:${code}`, JSON.stringify(payload)); const urls = payload.items.map((x) => x.media?.path).filter(Boolean).map((p) => `${getApiBase()}${p}`); if ("caches" in window) { const cache = await caches.open("velcore-display-v1"); await Promise.all(urls.map((url) => cache.add(url).catch(() => null))); } };
export default function DisplayRuntimePage() { const { displayCode } = useParams(); const [runtime, setRuntime] = useState(null); const [index, setIndex] = useState(0); const started = useRef(Date.now());
  const load = async () => { try { const next = await api.displayRuntime(displayCode); setRuntime(next); cacheRuntime(displayCode, next); } catch { const cached = localStorage.getItem(`display-runtime:${displayCode}`); if (cached) setRuntime(JSON.parse(cached)); } };
  useEffect(() => { load(); const heartbeat = setInterval(() => { if (runtime) api.displayHeartbeat({ displayCode, resolution: `${innerWidth}x${innerHeight}`, browser: navigator.userAgent, playlist: runtime.playlist?.name || "", uptime: Math.floor((Date.now() - started.current) / 1000), fullscreen: Boolean(document.fullscreenElement) }).catch(() => {}); }, 30000); return () => clearInterval(heartbeat); }, [displayCode, runtime?.playlist?.id]);
  useEffect(() => { document.documentElement.style.overflow = "hidden"; document.documentElement.requestFullscreen?.().catch(() => {}); const ws = new WebSocket(getApiBase().replace(/^http/, "ws") + `/display-center/ws/${displayCode}`); ws.onmessage = (e) => { if (JSON.parse(e.data).type === "reload") load(); }; const ping = setInterval(() => ws.readyState === 1 && ws.send("ping"), 25000); return () => { clearInterval(ping); ws.close(); document.documentElement.style.overflow = ""; }; }, [displayCode]);
  const items = runtime?.items || []; const item = items[index]; useEffect(() => { if (!item || items.length < 2) return; const id = setTimeout(() => setIndex((i) => (i + 1) % items.length), (item.duration_seconds || 15) * 1000); return () => clearTimeout(id); }, [item?.id, index, items.length]);
  if (!runtime) return <div className="grid h-screen place-items-center bg-black text-3xl text-white">Loading display…</div>; if (!item) return <div className="grid h-screen place-items-center bg-black text-3xl text-white">No active playlist</div>; return <main className={`h-screen w-screen overflow-hidden bg-black text-white ${item.transition === "fade" ? "animate-pulse" : ""}`}><RenderWidget item={item} /></main>; }
