import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../../api/client";
import { useLocale } from "../../context/LocaleContext";
import { date, panel } from "../productionProjects/projectUi";

export default function DeliveryHistoryPage() {
  const { t, locale } = useLocale();
  const [rows,setRows]=useState([]),[filters,setFilters]=useState({from:"",to:"",destination:"",project:"",vehicle:"",driver:""});
  useEffect(()=>{Promise.all([api.finishedTrips({status:"delivered"}),api.finishedTrips({status:"accepted"}),api.finishedVehicles(true),api.productionProjects({page_size:100})]).then(([a,b,v,p])=>{const vm=new Map((v.vehicles||[]).map(x=>[x.id,x])),pm=new Map((p.items||[]).map(x=>[x.id,x]));setRows([...(a.trips||[]),...(b.trips||[])].map(x=>({...x,vehicle:vm.get(x.vehicle_id),project:pm.get(x.project_id)})));});},[]);
  const visible=useMemo(()=>rows.filter(x=>{const when=x.arrived_at?new Date(x.arrived_at):null;return(!filters.from||when>=new Date(`${filters.from}T00:00:00`))&&(!filters.to||when<=new Date(`${filters.to}T23:59:59`))&&(!filters.destination||`${x.destination_city} ${x.destination_site}`.toLowerCase().includes(filters.destination.toLowerCase()))&&(!filters.project||String(x.project?.project_code||x.project_id).toLowerCase().includes(filters.project.toLowerCase()))&&(!filters.vehicle||x.vehicle?.registration_number===filters.vehicle)&&(!filters.driver||String(x.driver_user_id)===filters.driver);}),[rows,filters]);
  return <section className="space-y-4"><h1 className="text-2xl font-black">{t("checkpointD.deliveryHistory.title")}</h1><div className={`${panel} grid gap-2 sm:grid-cols-2 lg:grid-cols-3`}>{["from","to"].map(k=><input key={k} type="date" className="rounded-xl border p-2" value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}/>)}<input className="rounded-xl border p-2" placeholder={t("checkpointD.fields.destination")} value={filters.destination} onChange={e=>setFilters({...filters,destination:e.target.value})}/><input className="rounded-xl border p-2" placeholder={t("checkpointD.fields.project")} value={filters.project} onChange={e=>setFilters({...filters,project:e.target.value})}/><select className="rounded-xl border p-2" value={filters.vehicle} onChange={e=>setFilters({...filters,vehicle:e.target.value})}><option value="">{t("checkpointD.tracking.allVehicles")}</option>{[...new Map(rows.filter(x=>x.vehicle).map(x=>[x.vehicle.registration_number,x.vehicle])).values()].map(v=><option key={v.id}>{v.registration_number}</option>)}</select><select className="rounded-xl border p-2" value={filters.driver} onChange={e=>setFilters({...filters,driver:e.target.value})}><option value="">{t("checkpointD.tracking.allDrivers")}</option>{[...new Map(rows.filter(x=>x.driver_user_id).map(x=>[x.driver_user_id,x.driver_name_snapshot])).entries()].map(([id,n])=><option key={id} value={id}>{n||`#${id}`}</option>)}</select></div><div className="overflow-x-auto rounded-2xl border bg-[var(--brand-card)]"><table className="w-full min-w-[900px] text-sm"><thead><tr>{["trip","project","destination","dispatch","delivered","duration","vehicle","driver","status","deadline"].map(k=><th key={k} className="p-3 text-left">{t(`logisticsCenter.history.${k}`)}</th>)}</tr></thead><tbody>{visible.map(x=>{const duration=x.actual_departure_at&&x.arrived_at?Math.max(0,Math.round((new Date(x.arrived_at)-new Date(x.actual_departure_at))/3600000)):null;return <tr className="border-t" key={x.id}><td className="p-3"><Link className="font-bold" to={`/logistics/shipments/${x.id}`}>{x.trip_number}</Link></td><td>{x.project?.project_code||`#${x.project_id}`}</td><td>{x.destination_city} · {x.destination_site}</td><td>{date(x.actual_departure_at,locale)}</td><td>{date(x.arrived_at,locale)}</td><td>{duration==null?"—":t("logisticsCenter.history.hours",{count:duration})}</td><td>{x.vehicle?.registration_number||"—"}</td><td>{x.driver_name_snapshot||"—"}</td><td>{t(`checkpointD.status.${x.status}`)}</td><td>{x.delivery_deadline_at?<>{date(x.delivery_deadline_at,locale)}<span className="block text-xs">{t(`logisticsCenter.sla.${x.sla_state}`)}</span></>:t("logisticsCenter.history.deadlineUnavailable")}</td></tr>;})}</tbody></table>{!visible.length&&<div className="p-6">{t("checkpointD.deliveryHistory.empty")}</div>}</div></section>;
}
